# Generated by Django 2.2.9 on 2020-01-04 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dungeonroom', '0004_auto_20200104_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('stamina', models.PositiveIntegerField(default=0)),
                ('strength', models.PositiveIntegerField(default=0)),
                ('intelligence', models.PositiveIntegerField(default=0)),
                ('slot', models.CharField(choices=[('helmet', 'Helmet'), ('chest', 'Chest'), ('waist', 'Waist'), ('pants', 'Pants'), ('boots', 'Boots'), ('weapon', 'Weapon')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('player_level', models.PositiveIntegerField()),
                ('experience', models.PositiveIntegerField()),
                ('health', models.PositiveIntegerField(default=10)),
                ('mana_points', models.PositiveIntegerField(default=5)),
                ('stamina', models.PositiveIntegerField(default=1)),
                ('strength', models.PositiveIntegerField(default=1)),
                ('intelligence', models.PositiveIntegerField(default=1)),
                ('boots', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_boots', to='player.Item')),
                ('chest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_chest', to='player.Item')),
                ('helmet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_helmet', to='player.Item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dungeonroom.Room')),
                ('pants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_pants', to='player.Item')),
                ('waist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_waist', to='player.Item')),
                ('weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_weapon', to='player.Item')),
            ],
        ),
    ]
