# Generated by Django 2.2.7 on 2020-01-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20200104_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quality_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
