# Generated by Django 2.2.9 on 2020-01-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeonroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='num_rooms',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
