# Generated by Django 2.2.9 on 2020-01-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeonroom', '0002_floor_num_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='connections',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='pos_x',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='pos_y',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
