# Generated by Django 2.2.9 on 2020-01-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dungeonroom', '0003_auto_20200104_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='connection_east',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_east', to='dungeonroom.Room'),
        ),
        migrations.AddField(
            model_name='room',
            name='connection_north',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_north', to='dungeonroom.Room'),
        ),
        migrations.AddField(
            model_name='room',
            name='connection_south',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_south', to='dungeonroom.Room'),
        ),
        migrations.AddField(
            model_name='room',
            name='connection_west',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_west', to='dungeonroom.Room'),
        ),
    ]
